openapi: 3.0.0
info:
  title: watchlist
  version: '1.0'
  contact:
    name: Leor Brenman
    email: lbrenman@axway.com
    url: 'mailto:lbrenman@axway.com'
  description: Stock Watch List API
  license:
    name: None
    url: www.axway.com
  termsOfService: www.axway.com
servers:
  - url: 'http://localhost:8080/api'
    description: Local
paths:
  /watchlist:
    get:
      summary: Your GET endpoint
      tags:
        - Watch List
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/quote.yaml
              examples:
                example-1:
                  value:
                    - symbol: TXN
                      lastPrice: 174.74
                      change: 2.4199982
                    - symbol: AAPL
                      lastPrice: 157.58
                      change: 2.4900055
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
              examples:
                example-1:
                  value: Error
      operationId: get-watchlist
      description: Stock Watch List API
      parameters:
        - schema:
            type: array
            items:
              type: string
          in: query
          explode: false
          name: stocklist
          description: 'Comma separated list of stock symbols (e.g. aapl,txn,amzn)'
          required: true
          style: form
  /stockquote:
    get:
      summary: Your GET endpoint
      tags:
        - StockQuote
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/quote.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
      operationId: get-stockquote
      description: Stock Quote
      parameters:
        - schema:
            type: string
          in: query
          name: symbol
          description: Stock symbol (e.g. aapl)
components:
  schemas: {}
  securitySchemes:
    apikey:
      name: apikey
      type: apiKey
      in: header
tags:
  - name: StockQuote
    description: Stock quote
  - name: Watch List
    description: Watch List
security:
  - apikey: []
